### ISSUE TITLE
No navigation for "manage-workshop" api

### ISSUE THREAD

**Issue by dhrunia** [Virtual-Labs/outreach-portal#13]
n outreach coordinator account
home page is "http://testingserver.website/outreach/manage-workshop" if we click on logo it will redirected to the url "http://testingserver.website/outreach/".
there is noway to navigate to this url "http://testingserver.website/outreach/manage-workshop"
please add this functionality

**Comment by manjulasoftware** [comment]
Fixed .
Navigation bar is at My Dashboard
