### ISSUE TITLE
Fails to generate random password length as minimum 6 charachters on email invitation.

### ISSUE THREAD

**Issue by ksripathi** [Virtual-Labs/outreach-portal#16]
In outreach coordinator account,

On successful adding new nodal coordinator email notification will be sent to registered email id with  username as email_id and password as some default password (application will generate this)
when we try to login by using credentials sent on email notification sometimes application fails to login. 

Situation where it fails to login :

1) As per code written login should work with password length >=5. Most of the cases applicatioin is generating password  length as  >5 in these cases login is working fine. In some cases password length is =5. Here it fails to login.
2) Again on successfull login nodal coordinator may wants to change the password.
    there it is strictly mentioned that password should be 6-12 password length. It is accepting even if i change with 5 letters there is no validation. again it fails to login if i use new password.
3) When nodal coordinator wants to change the password there should be password,conform password feilds implemented.

Please look at following screeshots

![screenshot from 2015-09-01 23 21 22](https://cloud.githubusercontent.com/assets/8774380/9611939/640da1e6-5100-11e5-9099-3d528eab194f.png)
![screenshot from 2015-09-01 23 21 34](https://cloud.githubusercontent.com/assets/8774380/9611940/640fb71a-5100-11e5-8557-47c6e1f59f8f.png)

**Comment by manjulasoftware** [comment]
Fixed ,
password is 6 - 12 character length
