### ISSUE TITLE
Password length is not verified

### ISSUE THREAD

**Issue by ksripathi** [Virtual-Labs/outreach-portal#19]
In nodal & outreach coordinator account,

After successful login home page will ask to change the user password. There it is strictly mentioned that password should be 6-12 characters but still it is accepting <6 password length so that outreach or nodal coordinator can't login with new password.

**Comment by manjulasoftware** [comment]
fixed.

**Comment by ksripathi** [comment]
Its not fixed for outreach coordinator view
