### ISSUE TITLE
Foreign key is missing in va_user_details table

### ISSUE THREAD

**Issue by ksripathi** [Virtual-Labs/outreach-portal#23]
As per E-R diagramme shown there is a foreign key relationship b/w va_users and va_user_details tables.
There is no such implementation in current mysql-schema.

**Comment by karunakarvallapureddy** [comment]
Adding Foreign Key Relationships

**Comment by karunakarvallapureddy** [comment]
fixed

**Comment by karunakarvallapureddy** [comment]
fixed check once.
