### ISSUE TITLE
Admin logging is not working

### ISSUE THREAD

**Issue by ksripathi** [Virtual-Labs/outreach-portal#25]
When i login as admin using given credentials. I got following error

SELECT `vau`.`permission_id`, `vau`.`admin_id`, `vau`.`first_name`, `vau`.`last_name`, `vau`.`image` FROM (`va_admin_users` vau) WHERE `vau`.`admin_name` = 'admin@outreach.com' AND `status` = '1'

**Comment by karunakarvallapureddy** [comment]
fixed
