### ISSUE TITLE
Email validation should be follow RFC822

### ISSUE THREAD

**Issue by dhrunia** [Virtual-Labs/outreach-portal#9]
n outreach coordinator account,

While adding new nodal coordinator email is not verified properly instead it is accepting special characters such as #,%,^,,etc. This has to be fixed

**Comment by manjulasoftware** [comment]
Done

**Comment by dhrunia** [comment]
It does prompt that email address should contain valid email address. However it loads the upcoming workshops tab instead of staying in manage nodal centers tab.

**Comment by karunakarvallapureddy** [comment]
done
